
services:
  # Servidor Apache existente (PwotoSite.cl)
  apache-server:
    build: .
    container_name: apache-pwotosite
    networks:
      - dmz_network
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
      - ./config:/etc/apache2/sites-available
    restart: unless-stopped

  # Aplicaciones web vulnerables
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa-target
    networks:
      - dmz_network
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=password
    depends_on:
      - mysql-dvwa
    restart: unless-stopped

  mysql-dvwa:
    image: mysql:5.7
    container_name: mysql-dvwa
    networks:
      - lan_network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=password
    volumes:
      - dvwa-db:/var/lib/mysql
    restart: unless-stopped

  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop-target
    networks:
      - dmz_network
    ports:
      - "3000:3000"
    restart: unless-stopped

  webgoat:
    image: webgoat/goatandwolf
    container_name: webgoat-target
    networks:
      - dmz_network
    ports:
      - "8081:8080"
    restart: unless-stopped

  mutillidae:
    image: citizenstig/nowasp
    container_name: mutillidae-target
    networks:
      - dmz_network
    ports:
      - "8082:80"
    restart: unless-stopped

  # Contenedor atacante con Kali Linux
  kali-attacker:
    image: kalilinux/kali-rolling
    container_name: kali-attacker
    networks:
      - attacker_network
      - dmz_network
    tty: true
    stdin_open: true
    volumes:
      - ./lab-components/attack-tools:/tools
      - kali-home:/root
    command: /bin/bash
    restart: unless-stopped

  # Base de datos vulnerable en LAN
  mysql-target:
    image: mysql:5.7
    container_name: mysql-vulnerable
    networks:
      - lan_network
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=vulnerable_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-vulnerable:/var/lib/mysql
      - ./lab-components/vulnerable-apps/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # SSH Honeypot
  ssh-honeypot:
    image: cowrie/cowrie
    container_name: ssh-honeypot
    networks:
      - dmz_network
    ports:
      - "2222:2222"
    volumes:
      - cowrie-logs:/cowrie/var/log/cowrie
    restart: unless-stopped

  # Servidor FTP vulnerable
  ftp-vulnerable:
    image: stilliard/pure-ftpd
    container_name: ftp-vulnerable
    networks:
      - dmz_network
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=192.168.90.10
      - FTP_USER_NAME=ftpuser
      - FTP_USER_PASS=ftppass
      - FTP_USER_HOME=/home/ftpuser
    volumes:
      - ftp-data:/home/ftpuser
    restart: unless-stopped

networks:
  dmz_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
          gateway: 192.168.90.1
  
  lan_network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
  
  attacker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

volumes:
  dvwa-db:
  mysql-vulnerable:
  kali-home:
  cowrie-logs:
  ftp-data:
